echo "Cleaning up env vars"

# Wifi

unset PATTY_SSID
unset PATTY_PASS
unset SELMA_SSID
unset SELMA_PASS
unset VALE_SSID
unset VALE_PASS

# Database

unset DB_HOST
unset DB_PORT

unset POSTGRES_USER
unset POSTGRES_PASS

# Cache

unset CACHE_HOST
unset CACHE_PORT
unset CACHE_USER
unset CACHE_PASS

# Frontend

unset FRONTEND_HOST
unset FRONTEND_PORT

# IoT

unset IOT_DB_HOST
unset IOT_DB_PORT
unset IOT_DB_NAME
unset IOT_DB_USER
unset IOT_DB_PASS

unset IOT_CACHE_HOST
unset IOT_CACHE_PORT
unset IOT_CACHE_NAME
unset IOT_CACHE_USER
unset IOT_CACHE_PASS

unset IOT_API_HOST
unset IOT_API_PORT
unset IOT_API_CONTAINER_NAME

unset IOT_FORAGER_HOST
unset IOT_FORAGER_PORT

# Managers

unset SOLAR_MANAGER_HOST
SOLAR_MANAGER_PORT=8020

unset SOLAR_MANAGER_CACHE_HOST
unset SOLAR_MANAGER_CACHE_PORT
unset SOLAR_MANAGER_CACHE_NAME
unset SOLAR_MANAGER_CACHE_USER
unset SOLAR_MANAGER_CACHE_PASS

# Utilities

unset UTILITIES_DB_HOST
unset UTILITIES_DB_PORT
unset UTILITIES_DB_NAME
unset UTILITIES_DB_USER
unset UTILITIES_DB_PASS

unset UTILITIES_CACHE_HOST
unset UTILITIES_CACHE_PORT
unset UTILITIES_CACHE_NAME
unset UTILITIES_CACHE_USER
unset UTILITIES_CACHE_PASS

unset UTILITIES_API_HOST
unset UTILITIES_API_PORT
unset UTILITIES_API_CONTAINER_NAME

unset UTILITIES_SCRAPER_HOST
unset UTILITIES_SCRAPER_PORT

# Weather

unset WEATHER_DB_HOST
unset WEATHER_DB_PORT
unset WEATHER_DB_NAME
unset WEATHER_DB_USER
unset WEATHER_DB_PASS

unset WEATHER_CACHE_HOST
unset WEATHER_CACHE_PORT
unset WEATHER_CACHE_NAME
unset WEATHER_CACHE_USER
unset WEATHER_CACHE_PASS

unset WEATHER_API_HOST
unset WEATHER_API_PORT
unset WEATHER_API_CONTAINER_NAME

unset WEATHER_SCRAPER_HOST
unset WEATHER_SCRAPER_PORT

# Location

unset LOCATION_LATITUDE
unset LOCATION_LONGITUDE

# Open Weather Map

unset OWM_API_KEY

# Octopus Energy

unset OCTOPUS_ENERGY_API_KEY
unset ELECTRIC_METER_MPAN
unset ELECTRIC_METER_SERIAL_NUMBER
unset GAS_METER_MPRNGAS_METER_SERIAL_NUMBER

# Devices

unset MESH_SSID
unset MESH_PASSWORD

unset DEVICE_IP_MASK

unset MESH_BRIDGE_IP_LOCATION
unset MESH_BRIDGE_HOSTNAME
unset MESH_BRIDGE_LOCATION
unset MESH_BRIDGE_OTA_PASS

unset SOLAR_CONTROLLER_IP_LOCATION
unset SOLAR_CONTROLLER_HOSTNAME
unset SOLAR_CONTROLLER_LOCATION
unset SOLAR_CONTROLLER_OTA_PASS

unset WATER_BUTT_IP_LOCATION
unset WATER_BUTT_HOSTNAME
unset WATER_BUTT_LOCATION
unset WATER_BUTT_OTA_PASS

unset POND_IP_LOCATION
unset POND_HOSTNAME
unset POND_LOCATION
unset POND_OTA_PASS

unset AQUAPONICS_IP_LOCATION
unset AQUAPONICS_HOSTNAME
unset AQUAPONICS_LOCATION
unset AQUAPONICS_OTA_PASS