#!/bin/bash

devices=$(pwd)
root="$(dirname $devices)"
shared="$root/shared"
cpp="$shared/c++"
solar_controller="$devices/solar-controller"
water_butt="$devices/water-butt"
pond="$devices/pond"
aquaponics="$devices/aquaponics"

AsyncDHT="$cpp/AsyncDHT"      
AsyncMesh="$cpp/AsyncMesh"      
AsyncNTP="$cpp/AsyncNTP"      
AsyncOTA="$cpp/AsyncOTA"      
AsyncPZEM="$cpp/AsyncPZEM"     
AsyncSwitch="$cpp/AsyncSwitch"  
AsyncTracer="$cpp/AsyncTracer"   
AsyncWifi="$cpp/AsyncWifi"     
DeviceServer="$cpp/DeviceServer"  
ExecutionTimer="$cpp/ExecutionTimer"
Log="$cpp/Log"
MeasurementsState="$cpp/MeasurementsState"
TimeUtils="$cpp/TimeUtils"

rm -rf "$solar_controller/lib/AsyncDHT"
ln -s "$AsyncDHT" "$solar_controller/lib/AsyncDHT"
rm -rf "$solar_controller/lib/AsyncMesh"
ln -s "$AsyncMesh" "$solar_controller/lib/AsyncMesh"
rm -rf "$solar_controller/lib/AsyncNTP"
ln -s "$AsyncNTP" "$solar_controller/lib/AsyncNTP"
rm -rf "$solar_controller/lib/AsyncOTA"
ln -s "$AsyncOTA" "$solar_controller/lib/AsyncOTA"
rm -rf "$solar_controller/lib/AsyncPZEM"
ln -s "$AsyncPZEM" "$solar_controller/lib/AsyncPZEM"
rm -rf "$solar_controller/lib/AsyncSwitch"
ln -s "$AsyncSwitch" "$solar_controller/lib/AsyncSwitch"
rm -rf "$solar_controller/lib/AsyncTracer"
ln -s "$AsyncTracer" "$solar_controller/lib/AsyncTracer"
rm -rf "$solar_controller/lib/AsyncWifi"
ln -s "$AsyncWifi" "$solar_controller/lib/AsyncWifi"
rm -rf "$solar_controller/lib/DeviceServer"
ln -s "$DeviceServer" "$solar_controller/lib/DeviceServer"
rm -rf "$solar_controller/lib/ExecutionTimer"
ln -s "$ExecutionTimer" "$solar_controller/lib/ExecutionTimer"
rm -rf "$solar_controller/lib/Log"
ln -s "$Log" "$solar_controller/lib/Log"
rm -rf "$solar_controller/lib/MeasurementsState"
ln -s "$MeasurementsState" "$solar_controller/lib/MeasurementsState"
rm -rf "$solar_controller/lib/TimeUtils"
ln -s "$TimeUtils" "$solar_controller/lib/TimeUtils"

rm -rf "$solar_controller/shared"
ln -s "$shared" "$solar_controller/shared"

rm -rf "$water_butt/lib/AsyncDHT"
ln -s "$AsyncDHT" "$water_butt/lib/AsyncDHT"
rm -rf "$water_butt/lib/AsyncMesh"
ln -s "$AsyncMesh" "$water_butt/lib/AsyncMesh"
rm -rf "$water_butt/lib/AsyncNTP"
ln -s "$AsyncNTP" "$water_butt/lib/AsyncNTP"
rm -rf "$water_butt/lib/AsyncOTA"
ln -s "$AsyncOTA" "$water_butt/lib/AsyncOTA"
rm -rf "$water_butt/lib/AsyncPZEM"
ln -s "$AsyncPZEM" "$water_butt/lib/AsyncPZEM"
rm -rf "$water_butt/lib/AsyncSwitch"
ln -s "$AsyncSwitch" "$water_butt/lib/AsyncSwitch"
rm -rf "$water_butt/lib/AsyncTracer"
ln -s "$AsyncTracer" "$water_butt/lib/AsyncTracer"
rm -rf "$water_butt/lib/AsyncWifi"
ln -s "$AsyncWifi" "$water_butt/lib/AsyncWifi"
rm -rf "$water_butt/lib/DeviceServer"
ln -s "$DeviceServer" "$water_butt/lib/DeviceServer"
rm -rf "$water_butt/lib/ExecutionTimer"
ln -s "$ExecutionTimer" "$water_butt/lib/ExecutionTimer"
rm -rf "$water_butt/lib/Log"
ln -s "$Log" "$water_butt/lib/Log"
rm -rf "$water_butt/lib/MeasurementState"
ln -s "$MeasurementState" "$water_butt/lib/MeasurementState"
rm -rf "$water_butt/lib/TimeUtils"
ln -s "$TimeUtils" "$water_butt/lib/TimeUtils"

rm -rf "$water_butt/shared"
ln -s "$shared" "$water_butt/shared"

rm -rf "$pond/lib/AsyncDHT"
ln -s "$AsyncDHT" "$pond/lib/AsyncDHT"
rm -rf "$pond/lib/AsyncMesh"
ln -s "$AsyncMesh" "$pond/lib/AsyncMesh"
rm -rf "$pond/lib/AsyncNTP"
ln -s "$AsyncNTP" "$pond/lib/AsyncNTP"
rm -rf "$pond/lib/AsyncOTA"
ln -s "$AsyncOTA" "$pond/lib/AsyncOTA"
rm -rf "$pond/lib/AsyncPZEM"
ln -s "$AsyncPZEM" "$pond/lib/AsyncPZEM"
rm -rf "$pond/lib/AsyncSwitch"
ln -s "$AsyncSwitch" "$pond/lib/AsyncSwitch"
rm -rf "$pond/lib/AsyncTracer"
ln -s "$AsyncTracer" "$pond/lib/AsyncTracer"
rm -rf "$pond/lib/AsyncWifi"
ln -s "$AsyncWifi" "$pond/lib/AsyncWifi"
rm -rf "$pond/lib/DeviceServer"
ln -s "$DeviceServer" "$pond/lib/DeviceServer"
rm -rf "$pond/lib/ExecutionTimer"
ln -s "$ExecutionTimer" "$pond/lib/ExecutionTimer"
rm -rf "$pond/lib/Log"
ln -s "$Log" "$pond/lib/Log"
rm -rf "$pond/lib/MeasurementState"
ln -s "$MeasurementState" "$pond/lib/MeasurementState"
rm -rf "$pond/lib/TimeUtils"
ln -s "$TimeUtils" "$pond/lib/TimeUtils"

rm -rf "$pond/shared"
ln -s "$shared" "$pond/shared"

rm -rf "$aquaponics/lib/AsyncDHT"
ln -s "$AsyncDHT" "$aquaponics/lib/AsyncDHT"
rm -rf "$aquaponics/lib/AsyncMesh"
ln -s "$AsyncMesh" "$aquaponics/lib/AsyncMesh"
rm -rf "$aquaponics/lib/AsyncNTP"
ln -s "$AsyncNTP" "$aquaponics/lib/AsyncNTP"
rm -rf "$aquaponics/lib/AsyncOTA"
ln -s "$AsyncOTA" "$aquaponics/lib/AsyncOTA"
rm -rf "$aquaponics/lib/AsyncPZEM"
ln -s "$AsyncPZEM" "$aquaponics/lib/AsyncPZEM"
rm -rf "$aquaponics/lib/AsyncSwitch"
ln -s "$AsyncSwitch" "$aquaponics/lib/AsyncSwitch"
rm -rf "$aquaponics/lib/AsyncTracer"
ln -s "$AsyncTracer" "$aquaponics/lib/AsyncTracer"
rm -rf "$aquaponics/lib/AsyncWifi"
ln -s "$AsyncWifi" "$aquaponics/lib/AsyncWifi"
rm -rf "$aquaponics/lib/DeviceServer"
ln -s "$DeviceServer" "$aquaponics/lib/DeviceServer"
rm -rf "$aquaponics/lib/ExecutionTimer"
ln -s "$ExecutionTimer" "$aquaponics/lib/ExecutionTimer"
rm -rf "$aquaponics/lib/Log"
ln -s "$Log" "$aquaponics/lib/Log"
rm -rf "$aquaponics/lib/MeasurementState"
ln -s "$MeasurementState" "$aquaponics/lib/MeasurementState"
rm -rf "$aquaponics/lib/TimeUtils"
ln -s "$TimeUtils" "$aquaponics/lib/TimeUtils"

rm -rf "$aquaponics/shared"
ln -s "$shared" "$aquaponics/shared"
